[phases.setup]
nixPkgs = ["ffmpeg", "python311"]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium",
    "playwright install-deps"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
